Fails test if pylint produces errors

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -10,6 +10,15 @@ pip install --quiet --requirement test-requirements.txt
 # Run linting
 python -m pylint -f parseable textpipe | tee pylint.out
 
+# Fail build if Pylint returns fatal (1) | error (2)
+if [ $(($rc & 3)) -ne 0 ]; then
+    echo "Pylint failed"
+    exit 1
+else
+    echo "Pylint passed"
+    exit 0
+fi
+
 # Download languages needed for testing
 python -m spacy download nl > /dev/null
 python -m spacy download en > /dev/null
